name = 'Interplanetary Hugo Theme'
license = 'MIT'
licenselink = 'https://opensource.org/licenses/MIT'
description = 'Hugo Theme optimized for interplanetary usage on IPFS'
homepage = 'https://github.com/devidw/hugo-theme-interplanetary'
# demosite = ''
tags = ['ipfs', 'interplanetary', 'decentralized', 'light', 'dark', 'blog', 'responsive', 'dark mode', 'minimal']
features = ['widgets', 'search', 'tags', 'edit-on-github', 'header', 'sidebar', 'footer', 'custom-css', 'custom-js', 'toc', 'menu', 'mobile-menu']

[author]
  name = 'devidw'
  homepage = 'https://github.com/devidw'
