name = 'Content first Hugo Theme'
license = 'MIT'
licenselink = 'https://opensource.org/licenses/MIT'
description = 'Content first Hugo Theme'
homepage = 'https://github.com/devidw/hugo-theme-cik'
# demosite = ''
tags = ['light', 'dark', 'light mode', 'dark mode', 'blog', 'responsive', 'minimal', 'pagination',]
features = ['sections', 'header', 'footer', 'custom-css', 'custom-js', 'navigation', 'nav', 'math', 'asciidoc', 'asciidoctor', 'pagination',]

[author]
  name = 'devidw'
  homepage = 'https://github.com/devidw'
