name = 'Content first Hugo Theme'
license = 'MIT'
licenselink = 'https://opensource.org/licenses/MIT'
description = 'Content first Hugo Theme'
homepage = 'https://github.com/devidw/hugo-theme-interplanetary'
# demosite = ''
tags = ['light', 'dark', 'blog', 'responsive', 'dark mode', 'minimal']
features = ['sections', 'edit-on-github', 'header', 'sidebar', 'footer', 'custom-css', 'custom-js', 'toc', 'menu', 'mobile-menu']

[author]
  name = 'devidw'
  homepage = 'https://github.com/devidw'
