author: 
  name: David Wolf
  email: david@wolf.gdn
  # signature: signature/static-1.svg

themeColor: "#ff6961"

mainSections:
  - posts

icons:
  favicon: logo.svg
  touchIcon: logo.svg
  maskIcon: logo.svg

payments:
  - https://paypal.me/devidwolf
  - https://buymeacoffee.com/dwolf